number = set()
n=input("enter a number : ")
number.add(n)
n=input("enter a number : ")
number.add(n)
n=input("enter a number : ")
number.add(n)
n=input("enter a number : ")
number.add(n)
n=input("enter a number : ")
number.add(n)
n=input("enter a number : ")
number.add(n)
n=input("enter a number : ")
number.add(n)
n=input("enter a number : ")
number.add(n)

print(number)
